services:
  traefik:
    image: traefik:v3.1
    command: 
      - "--api.insecure=true" 
      - "--providers.docker"
      - "--providers.docker.network=traefik_network"
      - "--metrics.prometheus=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=mixmyxxe@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - traefik_network

  api:
    image: drifterz13/nest-vultr-deploy:${IMAGE_TAG}
    restart: on-failure:3
    environment:
      - PORT=8000
      - DATABASE_URL=file:/app/db/prod.db
    expose:
      - "8000"
    volumes:
      - db_data:/app/db
      - api_logs:/app/log
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.drifterz13.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"

volumes:
  db_data:
  api_logs:
    external: true
networks:
  traefik_network:
    external: true
